### ISSUE TITLE
Event for entering and leaving geofence

### ISSUE THREAD

**Issue by deepak-netsoft** [michaelmika/react-native-simple-native-geofencing#10]
Hello @michaelmika  
Thanks for the  library. What I want is callback function when user enter in the geofence and also when leaving the geofence. Please help

**Comment by alexandrethorigny** [comment]
Hello @deepak-netsoft, do you finally have found a solution?
I want to do the same thing in my project. Thanks.

**Comment by deepak-netsoft** [comment]
Hello @alexandrethorigny I have used react-native boundary library  Geofence Events

[Link](https://www.npmjs.com/package/react-native-boundary)

**Comment by michaelmika** [comment]
This simple geofencing library only allows to fire notifications when entering or leaving multiple monitored geofences. With the monitor-geofence you can also fire a specific react/JS function in the background (this is originally used to re-calculate the monitored geofences, when leaving a bigger zone, a.k.a. the monitoring geofence). If you want to trigger a specific react/JS function for multiple geofences however, feel free to add this functionality to this repo by using the same technique as it was done for the monitoring geofence (in android headlessJS is used & in iOS event triggers). If you have specific questions, feel free to ask. I will also accept pull requests. react-native-boundary might also be a good solution and a more actively maintained repo.
