### ISSUE TITLE
Fail to start geofencing

### ISSUE THREAD

**Issue by DuranMoodley** [michaelmika/react-native-simple-native-geofencing#11]
I keep getting the above error message but theres no details surrounding what the problem is. Can someone please assist.
Heres the code below
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React , {Component,useState, useEffect}  from 'react';

import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
  PermissionsAndroid
} from 'react-native';

import {
  Header,
  LearnMoreLinks,
  Colors,
  DebugInstructions,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';

import RNSimpleNativeGeofencing from 'react-native-simple-native-geofencing';

export default function index(props) {
    
  const [state, setState] = useState({
    organisationName: ' ',
    weighbridgeName: ' ',
    refreshing: false,
    isLoading: false,
    animating: true,
    dataItems: [],
    dialogVisible: false,
    errorMessage: ' ',
    query: '',
    films: [],
    isDropDownVisible: false,
    CurrentItemSelected : {},
    search: '' 
  })

  useEffect(() => {
  
    if(Platform.OS === 'android'){
      requestPermission();       
    }

  
   // startMonitoring();

    return () => {
      stopMonitoring();
    }

  }, [])

  const requestPermission = async () => {
    try {
      const granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
          {
            'title': 'Location permission',
            'message': 'Needed obviously'
          }
      )
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log("Granted Permission")
        InitializeGeofence();
      } else {
        console.log("Denied Permission")
      }
    } catch (err) {
      console.warn(err)
    }
  }

  return (
    <View><Text>Hello</Text></View>
  )
  function InitializeGeofence () {
    RNSimpleNativeGeofencing.initNotification(
      {
        channel: {
          title: "Message Channel Title",
          description: "Message Channel Description"
        },
        start: {
          notify: true,
          title: "Start Tracking",
          description: "You are now tracked"
        },
        stop: {
          notify: true,
          title: "Stopped Tracking",
          description: "You are not tracked any longer"
        },
        enter: {
          notify: true,
          title: "Attention",
          //[value] will be replaced ob geofences' value attribute
          description: "You entered a [value] Zone"
        },
        exit: {
          notify: true,
          title: "Left Zone",
          description: "You left a [value] Zone"
        }
      }
   );

   startMonitoring();
  }

  function startMonitoring(){
    let geofences = [
      {
        key: "geoNum1",
        latitude: -26.013260,
        longitude: 28.027290,
        radius: 50,
        value: "yellow"
      },
      {
        key: "geoNum2",
        latitude: -26.080356,
        longitude: 27.975600,
        radius: 100,
        value: "green"
      },
      {
        key: "geoNum3",
        latitude: -27.003601,
        longitude: 28.470620,
        radius: 150,
        value: "red"
      }
    ];
    RNSimpleNativeGeofencing.addGeofences(geofences, 3000000, fail());
  }

  function stopMonitoring(){
    RNSimpleNativeGeofencing.removeAllGeofences();
}

}

function fail(){
  console.log("Fail to start geofencing")
}

const styles = StyleSheet.create({
  scrollView: {
    backgroundColor: Colors.lighter,
  },
  engine: {
    position: 'absolute',
    right: 0,
  },
  body: {
    backgroundColor: Colors.white,
  },
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: Colors.black,
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
    color: Colors.dark,
  },
  highlight: {
    fontWeight: '700',
  },
  footer: {
    color: Colors.dark,
    fontSize: 12,
    fontWeight: '600',
    padding: 4,
    paddingRight: 12,
    textAlign: 'right',
  },
});

**Comment by michaelmika** [comment]
We need more information and please format your code better.

**Comment by JasleenKaurPanesar** [comment]
RNSimpleNativeGeofencing is coming undefined
