### ISSUE TITLE
how can I check if a coordinate is inside polygon with this library ?

### ISSUE THREAD

**Issue by byteab** [michaelmika/react-native-simple-native-geofencing#13]

**Comment by michaelmika** [comment]
This library uses the native geofence abilities from iOS & Android and therefore only works for circular geofences (see [android doc](https://developer.android.com/training/location/geofencing) & [iOS doc](https://developer.apple.com/documentation/corelocation/monitoring_the_user_s_proximity_to_geographic_regions) ). You could use several circular geofences to approximate a polygon, but it is not natively supported.
