### ISSUE TITLE
Unit of Radius used to create geofence.

### ISSUE THREAD

**Issue by lakshbhutani** [michaelmika/react-native-simple-native-geofencing#6]
let geofences = [
          {
            key: "geoNum1",
            latitude: 38.9204,
            longitude: -77.0175,
            radius: 200,
            value: "yellow"
          },
          {
            key: "geoNum2",
            latitude: 38.9248,
            longitude: -77.0258,
            radius: 100,
            value: "green"
          },
          {
            key: "geoNum3",
            latitude: 47.423,
            longitude: -122.084,
            radius: 150,
            value: "red"
          }
        ];
what is the unit of radius used to create geofence?

**Comment by michaelmika** [comment]
Radius is in meters. 
For choosing the best radius, see docs for [android](https://developer.android.com/training/location/geofencing#choose-the-optimal-radius-for-your-geofence). Apples Docs aren't as good however, but it should work properly with a radius > 100m.
