### ISSUE TITLE
Installation with Pods

### ISSUE THREAD

**Issue by murcul-bump** [michaelmika/react-native-simple-native-geofencing#7]
Hi, I am having issues linking this library, is there way to install via CocoaPods?

**Comment by michaelmika** [comment]
Have you tried to add the following to your Podfile and do `pod install`(and maybe before `pod deintegrate` for cleaning):
```
pod ‘RNSimpleNativeGeofencing’, :path => ‘../node_modules/react-native-simple-native-geofencing’
```

Not quite sure if it works with Cocoapods though. I recommend to link it as in the docs. Please tell me if it works with Cocoapods.

**Comment by murcul-bump** [comment]
@michaelmika Hey thanks for this, but unfortunately it fails and says it's unable to find the Podspec. I guess I will fallback to manual linking then.
