### ISSUE TITLE
Example fails on ios

### ISSUE THREAD

**Issue by suswariadla** [michaelmika/react-native-simple-native-geofencing#8]
I followed the example and it fails on ios with the following error 
TypeError: Cannot read property 'initNotification' of undefined

Seems to working fine on android.

Any thoughts, thanks!!

**Comment by michaelmika** [comment]
It sounds like you haven't installed the module properly for iOS. Have you linked it automatically (`$ react-native link react-native-simple-native-geofencing`) or manually? Are you using Cocoapods?

**Comment by suswariadla** [comment]
Hey,  @michaelmika Thanks for the solution which worked for me. There is another issue we are experiencing right now: 
the package breaks the app building on the ios simulator especially 12.2 version. The metro bundler never loads and the app just shows the splash screen...
We tested without the package being configured and with configured and it seems we have the trouble building the app with the package on 12.2 version. Any idea?

**Comment by michaelmika** [comment]
Sorry, I do not know any possible reason for it. Does it only crash in simulator? Please create a new topic if the problem persists.
